on:
  push:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7.2.0
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm
      - name: Install dependencies
        run: npm ci
      - name: Build and publish apk
        run: eas build -p android --profile apk